### ISSUE TITLE
GPU显存必须大于7G吗？我只想运行predict.py

### ISSUE THREAD

**Issue by Hustle-Tung** [feihuzhang/GANet#22]
首先感谢您的分享

我想要得到`kitti_stereo_2015`的视差图，所以只想运行`predict.py`
但是出错了，错误信息显示显存不够：
```bash
(tchs) d@ubuntu:~/GANet$ python predict.py --crop_height=384 --crop_width=1248 --data_path='kitti_stereo_2015/testing/' --test_list='lists/kitti2015_test.list' --save_path='result' --kitti2015=1 --resume='checkpoint/kitti2015_final.pth'
Namespace(crop_height=384, crop_width=1248, cuda=True, data_path='kitti_stereo_2015/testing/', kitti=0, kitti2015=1, resume='checkpoint/kitti2015_final.pth', save_path='result', test_list='lists/kitti2015_test.list')
===> Building model
=> loading checkpoint 'checkpoint/kitti2015_final.pth'
Traceback (most recent call last):
  File "predict.py", line 146, in <module>
    test(leftname, rightname, savename)
  File "predict.py", line 122, in test
    pre, second, prediction = model(input1, input2)
  File "/home/d/anaconda3/envs/tchs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/anaconda3/envs/tchs/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/d/anaconda3/envs/tchs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/GANet/models/GANet_deep.py", line 411, in forward
    disp0, disp1, disp2 = self.cost_agg(x, g)
  File "/home/d/anaconda3/envs/tchs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/GANet/models/GANet_deep.py", line 329, in forward
    x = self.sga1(x, g['sg1'])
  File "/home/d/anaconda3/envs/tchs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/GANet/models/GANet_deep.py", line 279, in forward
    x = self.SGA(x, k1, k2, k3, k4)
  File "/home/d/anaconda3/envs/tchs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/d/GANet/libs/GANet/modules/GANet.py", line 64, in forward
    result = SgaFunction()(input, g0, g1, g2, g3)
  File "/home/d/GANet/libs/GANet/functions/GANet.py", line 26, in forward
    temp_out = input.new().resize_(num, channels, depth, height, width).zero_()
RuntimeError: CUDA out of memory. Tried to allocate 424.00 MiB (GPU 0; 3.95 GiB total capacity; 2.80 GiB already allocated; 227.56 MiB free; 104.70 MiB cached)
(tchs) d@ubuntu:~/GANet$ nvidia-smi
Wed Jul  3 23:39:05 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 940MX       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P0    N/A /  N/A |    474MiB /  4046MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
```
我想知道如何解决？在哪里减小batchsize？
(我刚开始学习机器学习，请见谅)

**Comment by ACkuku** [comment]
decrease `--crop_height` and  `--crop_width`

**Comment by Hustle-Tung** [comment]
It raise another error:
```bash
(tchs) d@ubuntu:~/GANet$ python predict.py --crop_height=8 --crop_width=26 --data_path='kitti_stereo_2015/testing/' --test_list='lists/kitti2015_test.list' --save_path='result' --kitti2015=1 --resume='checkpoint/kitti2015_final.pth'
Namespace(crop_height=8, crop_width=26, cuda=True, data_path='kitti_stereo_2015/testing/', kitti=0, kitti2015=1, resume='checkpoint/kitti2015_final.pth', save_path='result', test_list='lists/kitti2015_test.list')
===> Building model
=> loading checkpoint 'checkpoint/kitti2015_final.pth'
Traceback (most recent call last):
  File "predict.py", line 146, in <module>
    test(leftname, rightname, savename)
  File "predict.py", line 112, in test
    input1, input2, height, width = test_transform(load_data(leftname, rightname), opt.crop_height, opt.crop_width)
  File "predict.py", line 76, in test_transform
    temp_data = temp_data[:, start_y: start_y + crop_height, start_x: start_x + crop_width]
TypeError: slice indices must be integers or None or have an __index__ method
```
Can I just decrease the batchsize to solve the initial problem?

**Comment by ACkuku** [comment]
the batchsize=1 in predict.py.  crop_height and crop_width must be multiple of 48.

**Comment by Hustle-Tung** [comment]
oh, sorry, I forgot it.

I execute the following command:
```bash
python predict.py --crop_height=192 --crop_width=624 --data_path='kitti_stereo_2015/testing/' --test_list='lists/kitti2015_test.list' --save_path='result' --kitti2015=1 --resume='checkpoint/kitti2015_final.pth'
```
It start running!

But I give it up. It runs for a long time. The laptop is too hot to continue running. I'll run this code until I have a better computer. 
This model is too GPU consuming

Thank you very much for your help.
