### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 48 96 3 3, expected input[1, 80, 96, 160] to have 96 channels, but got 80 channels instead

### ISSUE THREAD

**Issue by hzxie** [feihuzhang/GANet#31]
I use the following command to evaluate the performance on FlyingThings3D:

```
python predict.py --crop_height=540 \
                  --crop_width=960 \
                  --data_path='/home/hzxie/Datasets/FlyingThings3D/' \
                  --test_list='./lists/sceneflow_test.list' \
                  --save_path='./result/' \
                  --resume='./checkpoint/sceneflow_epoch_10.pth'
```

However, I got the following error:

```
Traceback (most recent call last):
  File "predict.py", line 151, in <module>
    test(leftname, rightname, savename)
  File "predict.py", line 122, in test
    pre, second, prediction = model(input1, input2)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hzxie/Development/GANet/models/GANet_deep.py", line 396, in forward
    x = self.feature(x)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hzxie/Development/GANet/models/GANet_deep.py", line 130, in forward
    x = self.conv1b(x, rem0)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hzxie/Development/GANet/models/GANet_deep.py", line 72, in forward
    x = self.conv2(x)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hzxie/Development/GANet/models/GANet_deep.py", line 36, in forward
    x = self.conv(x)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 48 96 3 3, expected input[1, 80, 96, 160] to have 96 channels, but got 80 channels instead
```

**Comment by feihuzhang** [comment]
Should be noticed that the crop_height and crop_width should be multiple of 48. So, you should set 576x960.

**Comment by hzxie** [comment]
@feihuzhang 
Thank you for your response.
Actually, I add an interpolate operation as follows:

```
 63     def forward(self, x, rem):
 64         x = self.conv1(x)
 65         rem = torch.nn.functional.interpolate(rem, x.shape[2:])
```
To solve the problem cause by the limitation of `crop_height` and `crop_width `.
After changing the crop size to 576x960, the problem still exists.

```
126         x = self.deconv1a(x, rem0)
127         rem0 = x
128 
129         # x.shape == torch.Size([1, 48, 96, 160])
130         # rem0.shape == torch.Size([1, 32, 96, 160])
131         x = self.conv1b(x, rem0)
132         rem1 = x
```
An exception was thrown at line 131. The channels cannot be matched with the pretrained model.
Could you tell me how to solve it?

**Comment by feihuzhang** [comment]
crop_height and crop_width is not a limitation. You do not need to use any upsampling or interpolation to solve the "problem". It use zero paddings to get a suitable input and will crop the result into 540x960 disparity map. You should remove the interpolation you added in order to run the prediction scripts.

**Comment by hzxie** [comment]
Yes. It works now.
