### ISSUE TITLE
Runing error at syncBN.

### ISSUE THREAD

**Issue by YvanYin** [feihuzhang/GANet#81]
I have successfully compiled the compile.sh.
My package version is torch=1.1.0, cuda=9.2, python=3.6.

When I run predict.sh, I get the following error. It seems that the error is caused by sync_BN.

Traceback (most recent call last):
  File "predict.py", line 168, in <module>
    test(leftname, rightname, savename)
  File "predict.py", line 134, in test
    prediction = model(input1, input2)
  File "/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/fast/users/a1730322/code/Depth_stereomatching/GANet-master/models/GANet_deep.py", line 390, in forward
    g = self.conv_start(x)	
  File "/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/fast/users/a1730322/code/Depth_stereomatching/GANet-master/models/GANet_deep.py", line 38, in forward
    x = self.bn(x)
  File "/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/fast/users/a1730322/code/Depth_stereomatching/GANet-master/libs/sync_bn/modules/sync_bn.py", line 121, in forward
    self.activation, self.slope).view(input_shape)
  File "/fast/users/a1730322/code/Depth_stereomatching/GANet-master/libs/sync_bn/functions/sync_bn.py", line 95, in forward
    y = sync_bn_gpu.batchnorm_forward(x, _ex, _exs, gamma, beta, ctx.eps)
RuntimeError: cudaGetLastError() == cudaSuccess ASSERT FAILED at src/gpu/sync_bn_cuda.cu:289, please report a bug to PyTorch. (BatchNorm_Forward_CUDA at src/gpu/sync_bn_cuda.cu:289)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f7f291b8441 in /home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f7f291b7d7a in /home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: BatchNorm_Forward_CUDA(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, float) + 0x2c7 (0x7f7f1c45d763 in /fast/users/a1730322/code/Depth_stereomatching/GANet-master/libs/sync_bn/build/lib/sync_bn_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x2564e (0x7f7f1c45b64e in /fast/users/a1730322/code/Depth_stereomatching/GANet-master/libs/sync_bn/build/lib/sync_bn_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x2575e (0x7f7f1c45b75e in /fast/users/a1730322/code/Depth_stereomatching/GANet-master/libs/sync_bn/build/lib/sync_bn_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x22cf7 (0x7f7f1c458cf7 in /fast/users/a1730322/code/Depth_stereomatching/GANet-master/libs/sync_bn/build/lib/sync_bn_gpu.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #14: THPFunction_apply(_object*, _object*) + 0x6b1 (0x7f7f6873a481 in /home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib/python3.6/site-packages/torch/lib/libtorch_python.so)

**Comment by feihuzhang** [comment]
Try to replace with NVIDIA-apex.
Replace the sync-bn with another version.
1) Install NVIDIA-Apex package https://github.com/NVIDIA/apex
      $ git clone https://github.com/NVIDIA/apex
      $ cd apex
      $ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
2) Revise the "GANet_deep.py":
add `import apex` 
change all `BatchNorm2d` and `BatchNorm3d` to `apex.parallel.SyncBatchNorm`
